name: CI Linux (ARM64)

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt update && sudo apt -y install build-essential libxkbcommon-dev zlib1g-dev libfreetype6-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libavcodec-dev libsdl2-dev libsdl-image1.2-dev libxml2-dev yasm

      - name: Configure Build
        run: |
          ./configure --disable-qt --enable-xdelta

      - name: Compile RA
        run: |
          make -j$(getconf _NPROCESSORS_ONLN) clean
          make -j$(getconf _NPROCESSORS_ONLN) info all

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
