name: CI Linux (ARM64)

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt update && sudo apt -y install build-essential libxkbcommon-dev zlib1g-dev libfreetype6-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libavcodec-dev libsdl2-dev libsdl-image1.2-dev libxml2-dev yasm

      - name: Configure Build
        run: |
          ./configure --disable-floathard --disable-neon --disable-caca --disable-parport --disable-winrawinput --enable-cheevos --enable-command --enable-lua --enable-networking --enable-materialui --enable-ozone --enable-rgui --enable-xmb --enable-egl --enable-kms --enable-qt --enable-wayland 	        --enable-opengles --enable-opengles3 --enable-opengles3_1 --enable-opengles3_2 --enable-opengl_core --enable-sdl2 --enable-vulkan --enable-vulkan_display --enable-alsa --enable-bluetooth --enable-crtswitchres --enable-pipewire --enable-pulse --enable-dbus --enable-hid --enable-libshake --enable-rpiled --enable-udev --enable-networkgamepad --enable-ssl --enable-systemd --enable-wifi --enable-thread_storage --enable-threads --enable-zlib

      - name: Compile RA
        run: |
          make -j$(getconf _NPROCESSORS_ONLN) clean
          make -j$(getconf _NPROCESSORS_ONLN) info all

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
